// @ts-ignore `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.
import openNextWorker from "./.open-next/worker.js";

const workerImagePattern = /^\/ex.*\.png$/i;

function withNoStoreHeaders(response: Response) {
  const headers = new Headers(response.headers);

  headers.set("Cache-Control", "no-store, no-cache, must-revalidate, max-age=0");
  headers.set("CDN-Cache-Control", "no-store");
  headers.set("Cloudflare-CDN-Cache-Control", "no-store");

  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    if (workerImagePattern.test(url.pathname)) {
      const sourceIp = request.headers.get("cf-connecting-ip") ?? "unknown";

      console.log(`[public-asset] ${request.method} ${url.pathname} ip=${sourceIp}`);

      if (!env.ASSETS) {
        return new Response("ASSETS binding is not configured.", { status: 500 });
      }

      const response = await env.ASSETS.fetch(request);
      return withNoStoreHeaders(response);
    }

    return openNextWorker.fetch(request, env, ctx);
  },
} satisfies ExportedHandler<CloudflareEnv>;

// @ts-ignore `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.
export { BucketCachePurge, DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
